### ISSUE TITLE
DeviceManagement_ManagedDevices Update Error

### ISSUE THREAD

**Issue by johnathanhall** [Microsoft/Intune-PowerShell-SDK#14]
In the documentation [ManagedDevices](https://github.com/Microsoft/Intune-PowerShell-SDK/blob/master/PowerShellCmdlets/Generated/SDK/DeviceManagement/ManagedDevices.cs) un the Method "Update_DeviceManagement_ManagedDevices" it has System.Object deviceCategory as a parameter. As this is the only reference I could find that might be able to assign a Device category to a device.
I'm getting an error when trying to update this field for a device Using this command:
Update-DeviceManagement_ManagedDevices -managedDeviceId $id -deviceCategory $category
![powershell category assign error](https://user-images.githubusercontent.com/45497218/49309992-e721fe00-f491-11e8-9ca1-2c2bac0db165.PNG)

I also notice that deviceCategory wasn't specified in the Microsoft Graph REST API [V1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-update?view=graph-rest-1.0) or [Beta](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-update?view=graph-rest-beta) documentation for Update managedDevice

Am I just missing something for the method call or it this a bug?

Thanks,

Johnathan

**Comment by johnathanhall** [comment]
I found a work around to do the same thing.
Instead of using` Update-DeviceManagement_ManagedDevices -managedDeviceId $id -deviceCategory $category` Or from the Preview `Update-IntuneManagedDevice -managedDeviceId $id -deviceCategory $category`
I used:
```
$DeviceID = "5d1ffe77-5767-45ef-8400-b7aa82e12591"
$DeviceCategoryID = '79891b7b-e26f-47ba-9e47-5a3dcf111e1d'
$uri = "https://graph.microsoft.com/beta/deviceManagement/managedDevices('$DeviceID')/deviceCategory/" + '$ref'
$JSON = @{ "@odata.id" = "https://graph.microsoft.com/beta/deviceManagement/deviceCategories/$DeviceCategory" } | ConvertTo-Json
Invoke-RestMethod -Uri $uri -Headers $authToken -Method Put -Body $JSON -ContentType "application/json"
```
Still not sure why Update-IntuneManagedDevice can't assign a category though.

**Comment by John-Matlock** [comment]
I'm having this same problem.

**Comment by timmyit** [comment]
> In the documentation [ManagedDevices](https://github.com/Microsoft/Intune-PowerShell-SDK/blob/master/PowerShellCmdlets/Generated/SDK/DeviceManagement/ManagedDevices.cs) un the Method "Update_DeviceManagement_ManagedDevices" it has System.Object deviceCategory as a parameter. As this is the only reference I could find that might be able to assign a Device category to a device.
> I'm getting an error when trying to update this field for a device Using this command:
> Update-DeviceManagement_ManagedDevices -managedDeviceId $id -deviceCategory $category
> ![powershell category assign error](https://user-images.githubusercontent.com/45497218/49309992-e721fe00-f491-11e8-9ca1-2c2bac0db165.PNG)
> 
> I also notice that deviceCategory wasn't specified in the Microsoft Graph REST API [V1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-update?view=graph-rest-1.0) or [Beta](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-update?view=graph-rest-beta) documentation for Update managedDevice
> 
> Am I just missing something for the method call or it this a bug?
> 
> Thanks,
> 
> Johnathan

I see the same issue when trying to use Update-DeviceManagement_ManagedDevices when trying to update names on iOS devices. But using Invoke-Restmethod works fine so Its something wrong with the cmdlet.

**Comment by nsoy** [comment]
investigating..

**Comment by timmyit** [comment]
> investigating..

Awesome, let us know if there's anything we can do to help.

**Comment by nsoy** [comment]
I confirm what @johnathanhall reported above. Since this route is not exposed in the v1.0 schema, the only way to set categories on IntuneManagedDevices is via direct Invoke-RestMethod to the beta route.
$uri = "https://graph.microsoft.com/**beta**/deviceManagement/managedDevices('$DeviceID')/deviceCategory/" + '$ref'
$JSON = @{ "@odata.id" = "https://graph.microsoft.com/beta/deviceManagement/deviceCategories/$DeviceCategory" } | ConvertTo-Json
Invoke-RestMethod -Uri $uri -Headers $authToken -Method Put -Body $JSON -ContentType "application/json"

**Comment by mkalees1** [comment]
Update-IntuneManagedDevice -managedDeviceId $deviceID  -deviceCategoryDisplayName $Displayname

Am also getting the same error. Any fix on this

**Comment by rohitramu** [comment]
You can change the schema used by the module to "beta" by running the following command:
```PowerShell
Update-MSGraphEnvironment -SchemaVersion 'beta'
```

After this, you should only use the `Invoke-MSGraphRequest` cmdlet to make calls to Graph, since the standard (generated) cmdlets might not have the properties or entities you would like to use in the "beta" schema.  Using the standard cmdlets (e.g. `Update-IntuneManagedDevice` or `Update-DeviceManagement_ManagedDevices`) might result in unexpected behavior.  To achieve the same as @johnathanhall's example above, you can do the following:
```PowerShell
# Get the device ID and device category ID to associate
$DeviceID = "5d1ffe77-5767-45ef-8400-b7aa82e12591"
$DeviceCategory = '79891b7b-e26f-47ba-9e47-5a3dcf111e1d'

# Create the request body which would associate the two objects
$requestBody = @{ "@odata.id" = "https://graph.microsoft.com/beta/deviceManagement/deviceCategories/$DeviceCategory" }

# Make the call to Graph which will create the association
Invoke-MSGraphRequest -HttpMethod PUT -Url "deviceManagement/managedDevices('$DeviceID')/deviceCategory/`$ref" -Body $requestBody
```

**Comment by cmcapellan** [comment]
Small typo...for
``Invoke-MSGraphRequest -HttpMethod PUT -Url "deviceManagement/managedDevices/$DeviceID/deviceCategory/`$ref" -Body $requestBody
``
should be `-Content`, not `-Body`

**Comment by rohitramu** [comment]
Oops, thanks for pointing that out @cmcapellan.  I've fixed it now in the sample code.

**Comment by SamSepiolWarden** [comment]
Still an issue on the cmdlet Update-MgDeviceManagementmanagedDevice or that was fixed ?
